# Use postgres/example user/password credentials
version: '3'

services:
  api: 
    container_name: echofy_api
    build:
      dockerfile: config/docker/Dockerfile.api
      context: .
    env_file:
      - ./src/app/api/.env
      - ./src/app/api/.spotify.env
    restart: always
    ports: 
      - "8000:8000" 
  db:
    container_name: spotify_db
    build:
      dockerfile: config/docker/Dockerfile.postgres
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    restart: always
    ports:
      - "5432:5432"
  redis:
    container_name: echofy_redis
    build: 
      context: .
      dockerfile: config/docker/Dockerfile.redis
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=
    ports:
      - "6379:6379"