basePath: /api
definitions:
  response.ArtistDTO:
    properties:
      description:
        type: string
      founded_at:
        type: string
      id:
        type: string
      members:
        items:
          $ref: '#/definitions/response.ArtistDTO'
        type: array
      name:
        type: string
      spotify_url:
        type: string
      super_artist_id:
        type: string
      terminated_at:
        type: string
    type: object
  response.ErrorMessage:
    properties:
      duplicated_fields:
        items:
          type: string
        type: array
      invalid_fields:
        items:
          $ref: '#/definitions/response.InvalidField'
        type: array
      message:
        type: string
      status_code:
        type: integer
    type: object
  response.InvalidField:
    properties:
      description:
        type: string
      field_name:
        type: string
    type: object
  response.PlaylistDTO:
    properties:
      description:
        type: string
      followers_amount:
        type: integer
      id:
        type: string
      name:
        type: string
      song_amount:
        type: integer
    type: object
  response.SongDTO:
    properties:
      album_id:
        type: string
      artists:
        items:
          $ref: '#/definitions/response.ArtistDTO'
        type: array
      duration:
        type: integer
      id:
        type: string
      name:
        type: string
      release_date:
        type: string
    type: object
info:
  contact:
    email: evs10@aluno.ifal.edu.br
    name: Emanuel Vilela
  description: Aplicação de artistas do spotify
  title: ECHOFY API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: "Rota que permite que um usuário se autentique no sistema utilizando
        seu endereço de e-mail e senha.\n| E-mail              | Senha     | Função
        \                                                           |\n|---------------------|-----------|-------------------------------------------------------------------|\n|
        admin@ifal.edu.br   | Test1234! | Usuário comum do sistema\t\t\t\t\t\t\t\t\t\t
        \ |"
      operationId: Login
      produces:
      - application/json
      responses:
        "400":
          description: Requisição mal formulada.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "401":
          description: Usuário não autorizado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "403":
          description: Acesso negado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "422":
          description: Algum dado informado não pôde ser processado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados não está disponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Fazer login no sistema
      tags:
      - Rotas de autenticação
  /user/playlist/{playlistID}:
    get:
      description: Rota que permite que se busque todas as informações de uma playlist
      operationId: GetPlaylistID
      parameters:
      - default: 7pCvSVfjcnOw6AFJNZZ4bN
        description: ID da playlist.
        in: path
        name: playlistID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Requisição realizada com sucesso.
          schema:
            $ref: '#/definitions/response.PlaylistDTO'
        "401":
          description: Usuário não autorizado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "403":
          description: Acesso negado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "422":
          description: Algum dado informado não pôde ser processado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados não está disponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Buscar os dados de uma playlist
      tags:
      - Rotas do usuário
  /user/playlist/{playlistID}/songs:
    get:
      description: Rota que permite que se busque todas as músicas de uma determinada
        playlist
      operationId: GetSongsByPlaylistID
      parameters:
      - default: 7pCvSVfjcnOw6AFJNZZ4bN
        description: ID da playlist.
        in: path
        name: playlistID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Requisição realizada com sucesso.
          schema:
            items:
              $ref: '#/definitions/response.SongDTO'
            type: array
        "401":
          description: Usuário não autorizado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "403":
          description: Acesso negado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "422":
          description: Algum dado informado não pôde ser processado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados não está disponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Buscar todas as músicas de uma playlist
      tags:
      - Rotas do usuário
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
